### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dbkaplun** [barisbalic/genoset-alcohol-flush-reaction#1]
``` js
> var query = alcoholFlushReaction.extreme();
TypeError: undefined is not a function
    at Object.module.exports.extreme (/Users/dan/node_modules/genoset-alcohol-flush-reaction/index.js:5:21)
    at repl:1:34
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
```

**Comment by barisbalic** [comment]
Looks like I had notifications turned off for this, sorry for the long delay, I should get a chance to look at this next week, although it's likely a bit late to help you out :(
